---
title: "Simulation with Null Controls"
author: "Alex Franks"
date: 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(colorspace)
library(tidybayes)
library(cmdstanr)
options(mc.cores=4)
source("../utility_functions.R")
```

## Generate simulated data

- $q=10$ outcomes, $m=2$ latent confounders.  Confounding explains 50\% of the treatment variance
- Make a heat map of gamma (paper Figure ***)

```{r}
# model #
R2 <- 0.5
q <- 10
m <- 2
sigma2_t <- 1
R2 <- 0.5
set.seed(123)
B <- rstiefel::rustiefel(m, 1) * sqrt(sigma2_t * R2)
B[2] <- -B[2]
sigma2_y <- diag(q)

n = 1000

# t <- rbinom(n=n, size=1, prob=p_t)
t <- rnorm(n, 0, 1)

gamma0 <- matrix(0, nrow=q, ncol=m)
gamma0[1:(q/3), 1] <- seq(1, 2, length.out=floor(q/3)) / 2
gamma0[floor(q/3+1):floor(2*q/3), 2] <- -1*seq(1, 2, length.out=floor(q/3)) / 2
gamma0[floor(2*q/3+1):q, ] <- cbind(1*seq(1, 2, length.out=ceiling(q/3)), 1*seq(1, 2, length.out=ceiling(q/3))) / 3

gamma0[2, ] <- -1*gamma0[2, ]
gamma0[10, ] <- -1*gamma0[10, ]

u <- sapply(t, function(ti) {
    mvtnorm::rmvnorm(1, mean=B / sigma2_t * ti, sigma=diag(1, m) - B %*% t(B) / sigma2_t)
}) %>% t

sigma_u_t_neg_half <- chol(solve(diag(m) - B %*% t(B) / sigma2_t))

mu_yt <- c(0, 0, 1, rep(1, q-4), 0)  #rnorm(q)


y = as.matrix(t) %*% mu_yt + as.matrix(u) %*% sigma_u_t_neg_half %*% t(gamma0) + mvtnorm::rmvnorm(n, mean = rep(0, q), sig=sigma2_y)

colnames(y) = paste0("y", 1:q)

## tau_naive <- colMeans(y[t==1, ]) - colMeans(y[t==0, ])
tau_naive <- coef(lm(y ~ t))["t", ]

tau_naive
tau_naive - t(B) %*% sigma_u_t_neg_half %*% t(gamma0) /sigma2_t
data_list <- list(K=ncol(y), J=1, N=nrow(y), M=2, x=matrix(t, ncol=1), y=scale(y))

sm <- cmdstanr::cmdstan_model("../stan/multivariate_regression.stan")




tibble(expand.grid(outcome=1:10, col=1:2)) %>% 
  mutate(Value = as.numeric(gamma0)) %>%  
  ggplot(aes(x=col, y=forcats::fct_rev(as.factor(outcome)))) + 
  geom_tile(aes(fill=Value), col="black") + 
  geom_text(aes(label=round(Value, 2)), col="black") + 
  colorspace::scale_fill_continuous_diverging() + theme_bw() +
  theme(panel.grid = element_blank(), 
        panel.border = element_blank(),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        # axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        plot.title = element_text(hjust = 0.5)) + 
  xlab("") + ylab("") + ggtitle(expression(Gamma)) +
  theme(text = element_text(size=20))
ggsave("gamma_plot.pdf", height=5, width=3)

```

## Inference

```{r}

## By default, don't run sampler
run_sampler <- TRUE


if(run_sampler) {
 stan_results <- stan_results <- sm$sample(data_list)
 saveRDS(stan_results, file="simulation_1000_2_gauss_2.RDS")
} else {
  stan_results <- readRDS("simulation_1000_2_gauss_2.RDS")
}

naive_estimates <- stan_results %>% spread_draws(beta[K, J]) %>% 
  group_by(J, K) %>% 
  summarize(q025=quantile(beta, 0.025), 
            q975=quantile(beta, 0.975)) %>%
  mutate(sig = sign(q025*q975)==1) %>% 
  mutate(feature = colnames(y)) %>% 
  filter(J==1) %>% 
  arrange(desc(q025)) %>% relocate(feature, q025, q975)
naive_estimates


sdy <- attr(scale(y), "scaled:scale")
muy <- attr(scale(y), "scaled:center")


NC_index <- 1
R2 <- 0.5
tr <- t
beta_w_norm <- get_beta_w_norm(stan_results, data_list, NC_index=NC_index, 
                               marginal_sensitivity_param = FALSE, 
                               R2_no_nc=R2, R2_nc = R2, sdy=sdy)



orig_color = "#023FA5"
orig_color = "black"
nc_color = "#CC1C2F"
effect_intervals <- beta_w_norm %>% 
  group_by(K) %>% summarize(lower_naive=quantile(Naive, 0.025, na.rm=TRUE),
                            upper_naive=quantile(Naive, 0.975, na.rm=TRUE),
                            lower_init=quantile(R2_lwr, 0.025, na.rm=TRUE),
                            upper_init=quantile(R2_upr, 0.975, na.rm=TRUE),
                            lower_nc=quantile(R2_nc_lwr, 0.025, na.rm=TRUE),
                            upper_nc=quantile(R2_nc_upr, 0.975, na.rm=TRUE),
                            lower_rv_init = quantile(abs(rv_init), 0.05, na.rm=TRUE),
                            lower_rv_nc = quantile(abs(rv_nc), 0.05, na.rm=TRUE), 
                            lower_rv_nc_cond = quantile(abs(rv_nc_cond), 0.05, na.rm=TRUE),                             
                            lower_rv_ch = quantile(abs(rv_ch), 0.05, na.rm=TRUE),
                            lower_xrv = quantile(abs(xrv), 0.05, na.rm=TRUE)) %>% 
  mutate(K = as.character(1:10))

nc_plot_index <- which(effect_intervals$K %in% c(1))  

rv_nc <- round(abs(effect_intervals$lower_rv_nc), 2)
rv_nc_cond <- format(rv_nc-rv_nc[1], nsmall=2)
rv_nc <- format(rv_nc, nsmall=2)

text_diff <- c(0, 0.35, 0.6, 0.85)
text_loc <- 2.1 + text_diff

nc_bayes_plot <- effect_intervals %>%
  ggplot() + 
  geom_segment(aes(x=forcats::fct_inorder(K), xend=forcats::fct_inorder(K), 
                              y=lower_init, yend=upper_init, col='nuc50'), alpha=0.5, size=2) + 
  geom_segment(aes(x=forcats::fct_inorder(K), xend=forcats::fct_inorder(K), 
                   y=lower_nc, yend=upper_nc, col='null'), 
               size=3, alpha=0.8) +  
  ## CH RVS  
  geom_text(aes(x=forcats::fct_inorder(K), y = rep(text_loc[4], 10), 
                label=ifelse(sign(lower_naive) == sign(upper_naive), format(round(abs(lower_rv_ch), 2), nsmall=2), "X")), fontface="bold") + 
  ## XRVS
  geom_text(aes(x=forcats::fct_inorder(K), y = rep(text_loc[3], 10), 
                label=ifelse(sign(lower_naive) == sign(upper_naive), format(round(abs(lower_xrv), 2), nsmall=2), "X")), fontface="bold") + 
  ## Factor RV  
  geom_text(aes(x=forcats::fct_inorder(K), y = rep(text_loc[2], 10), 
                label=ifelse(sign(lower_naive) == sign(upper_naive), format(round(abs(lower_rv_init), 2), nsmall=2), "X")), fontface="bold") + 
  ## Factor + NC RV
  geom_text(aes(x=forcats::fct_inorder(K), y = rep(text_loc[1], 10), 
              label=rv_nc_cond), fontface="bold", nudge_x=0, nudge_y=.08, size=3) + 
  geom_text(aes(x=forcats::fct_inorder(K), y = rep(text_loc[1], 10), 
            label=rv_nc), fontface="bold", nudge_x=0, nudge_y=-.16, size=3) + 
  geom_segment(aes(x=as.numeric(K)-.25, xend=as.numeric(K)+.25, y=text_loc[1]-.04, yend=text_loc[1]-.04)) + 
  
    geom_text(data=tibble(), aes(label=c(as.character(expression(RV["c=1"]^Gamma)), 
                                       as.character(expression(RV^Gamma)), "XRV", 
                                       as.character(expression(RV^1))), x=rep(-.2, 4), y=text_loc), 
            fontface="bold", hjust=0, col="dark blue", parse=TRUE) +
  geom_point(aes(x=nc_plot_index, y=rep(0, length(nc_plot_index))), size=3, colour=nc_color, alpha=0.5, data=tibble()) +
  theme_bw(base_size=16) + 
  xlab("Outcome") + ylab("Treatment Effect") +
  geom_hline(yintercept=0, linetype="dashed") +
  geom_segment(x=2.5, xend=9.5, y=1, yend=1, linetype = "dashed", col="blue") +
  geom_segment(x=0, xend=2.5, y=0, yend=0, linetype = "dashed", col="blue") +
  geom_segment(x=9.5, xend=10.5, y=0, yend=0, linetype = "dashed", col="blue") +
  scale_color_manual(name="", labels = c("Original", expression(Y[1]~" is null")),
                     values=c(nuc50="blue", 'null'=nc_color)) +
  ggtitle( expression("Posterior Credible Regions ("~R[paste(T,'~',U)]^2<=~"50%)")) + expand_limits(x=-.25)
nc_bayes_plot
ggsave(nc_bayes_plot, filename="nc_sim_plot_w_uncertainty3.pdf", width=8, height=4) 
```


